### ISSUE TITLE
Image file missing

### ISSUE THREAD

**Issue by relu** [stas/pos#2]
```
SEVERE: Cannot read Menu.Root resource. Trying defaut menu.
com.openbravo.pos.scripting.ScriptException: Sourced file: inline evaluation of: ``//    Openbravo POS is a point of sales application designed for touch screens.  . . . '' : Method Invocation group.addPanel
    at com.openbravo.pos.scripting.ScriptEngineBeanshell.eval(ScriptEngineBeanshell.java:62)
    at com.openbravo.pos.forms.JPrincipalApp.getScriptMenu(JPrincipalApp.java:135)
    at com.openbravo.pos.forms.JPrincipalApp.<init>(JPrincipalApp.java:116)
    at com.openbravo.pos.forms.JRootApp.openAppView(JRootApp.java:484)
    at com.openbravo.pos.forms.JRootApp.access$000(JRootApp.java:54)
    at com.openbravo.pos.forms.JRootApp$AppUserAction.actionPerformed(JRootApp.java:456)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2318)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:242)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:236)
    at java.awt.Component.processMouseEvent(Component.java:6288)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3267)
    at java.awt.Component.processEvent(Component.java:6053)
    at java.awt.Container.processEvent(Container.java:2041)
    at java.awt.Component.dispatchEventImpl(Component.java:4651)
    at java.awt.Container.dispatchEventImpl(Container.java:2099)
    at java.awt.Component.dispatchEvent(Component.java:4481)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4577)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4238)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4168)
    at java.awt.Container.dispatchEventImpl(Container.java:2085)
    at java.awt.Window.dispatchEventImpl(Window.java:2478)
    at java.awt.Component.dispatchEvent(Component.java:4481)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:643)
    at java.awt.EventQueue.access$000(EventQueue.java:84)
    at java.awt.EventQueue$1.run(EventQueue.java:602)
    at java.awt.EventQueue$1.run(EventQueue.java:600)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:98)
    at java.awt.EventQueue$2.run(EventQueue.java:616)
    at java.awt.EventQueue$2.run(EventQueue.java:614)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:613)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: Sourced file: inline evaluation of: ``//    Openbravo POS is a point of sales application designed for touch screens.  . . . '' : Method Invocation group.addPanel : at Line: 111 : in file: inline evaluation of: ``//    Openbravo POS is a point of sales application designed for touch screens.  . . . '' : group .addPanel ( "/com/openbravo/images/time_clock22.png" , "Menu.CheckInCheckOut" , "com.openbravo.pos.epm.JPanelEmployeePresence" ) 
```

Se pare că lipsește `/com/openbravo/images/time_clock22.png`, cu un:

```
touch src-beans/com/openbravo/images/time_clock22.png
```

am recompilat și a funcționat

PS: Ai văzut [acest thread](http://bravoforge.com/plugins/espforum/view.php?group_id=101&forumid=434922&topicid=7010812&page=1)? S-ar putea să te ajute, măcar pe parte de fișiere lipsă, dacă nu mai mult, arhiva aia.

EDIT: am mai găsit [ăsta](http://forge.openbravo.com/plugins/espforum/view.php?group_id=101&forumid=434922&topicid=7006646) și [ăsta de aici](http://forge.openbravo.com/projects/freePOS). Dacă îți ușurează munca oricare dintre astea, go ahead!

**Comment by stas** [comment]
FreePOS nu are nimic cod acolo. Ce am portat eu e din openPOS, însă am editat manual diff-u până mi-o mers patch-u :/

Sincer patch-ul nu e testat dacă merge totul, o să mai adaug ce resurse lipsesc, însă în principiu ar trebui să fie ok totul.
Keep in touch. Azi bag și restu modificărilor și mai testez.
