### ISSUE TITLE
Null pointer exception on Sales/Edit Sales panels

### ISSUE THREAD

**Issue by relu** [stas/pos#3]
```
com.openbravo.pos.forms.BeanFactoryException: java.lang.NullPointerException
    at com.openbravo.pos.forms.JRootApp.getBean(JRootApp.java:331)
    at com.openbravo.pos.forms.JPrincipalApp.showTask(JPrincipalApp.java:356)
    at com.openbravo.pos.forms.MenuPanelAction.actionPerformed(MenuPanelAction.java:46)
    at com.openbravo.pos.forms.JPrincipalApp.activate(JPrincipalApp.java:274)
    at com.openbravo.pos.forms.JRootApp.openAppView(JRootApp.java:494)
    at com.openbravo.pos.forms.JRootApp.access$000(JRootApp.java:54)
    at com.openbravo.pos.forms.JRootApp$AppUserAction.actionPerformed(JRootApp.java:456)
        ..........
```

Probabil știi deja de asta și chiar lucrezi la ea :)

Off-topic: Jaco are nevoie de la tine de un fel de... schemă cu structura curentă a bazei de date (în pincipiu doar ceea ce e legat de materiale, produse, rețete, atribute și taxe, mai exact ceea ce ține de datele care trebuiesc introduse pentru un restaurant). Trebuie să fac apoi un script ceva să iau datele alea din ce format ne vor da ăștia produsele and what not și să le introduc în baza de date mai automatizat așa... Când poți, merci!

**Comment by stas** [comment]
Scriptu care era la OpenTPV ar trebui sa mearga si aici.
